agent_id: default-agent
name: Default Search Agent
tools:
  - search
  - web_search
  - calculate
llm_model: openrouter-deepseek
prompt_template: |
  你是一个智能助手。基于用户的输入，使用以下工具来完成任务：
  
  工具列表：
  {tools}
  
  历史记录：
  {history}
  
  用户输入：{input_text}
  
  思考并一步步完成任务。如果需要使用工具，使用格式：
  行动: 工具名称, 参数
  
  如果已经得到答案，使用格式：
  最终答案: 你的答案 